on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

name: CI

jobs:
  test:
    name: Build and Test
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
        rust:
          - stable
          - nightly
        include:
          - target: x86_64-pc-windows-msvc
            image: windows-latest
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-latest
          - target: aarch64-apple-darwin
            image: macos-latest
    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }} && rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --workspace --exclude mcumgr-toolkit-python --exclude mcumgr-toolkit-web

      - name: Test
        run: cargo test --release --target ${{ matrix.target }} --workspace --exclude mcumgr-toolkit-python --exclude mcumgr-toolkit-web --verbose $DOCTEST_XCOMPILE -- --test-threads 1

  build-examples:
    name: Build Examples
    runs-on: ubuntu-latest
    needs: [lints, docs]
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --examples --all-features --release

  build-cli:
    name: Build CLI
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - linux
          - macos
        include:
          - os: windows
            image: windows-latest
            target: x86_64-pc-windows-msvc
            extension: ".exe"
          - os: linux
            image: ubuntu-latest
            target: x86_64-unknown-linux-musl
            extension: ""
          - os: macos
            image: macos-latest
            target: aarch64-apple-darwin
            extension: ""
    runs-on: ${{ matrix.image }}

    env:
      RUSTFLAGS: "-C target-feature=+crt-static"

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --bin mcumgrctl --target ${{ matrix.target }}

      - name: Collect binary
        run: cp target/${{ matrix.target }}/release/mcumgrctl${{ matrix.extension }} mcumgrctl-${{ matrix.os }}${{ matrix.extension }}

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: mcumgrctl-${{ matrix.os }}
          path: mcumgrctl-${{ matrix.os }}${{ matrix.extension }}
          retention-days: 7

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: mcumgrctl-${{ matrix.os }}${{ matrix.extension }}

  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    needs: [lints, docs]
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo-msrv
        run: cargo binstall --version 0.18.4 --no-confirm cargo-msrv

      - name: Check MSRV of mcumgr-toolkit
        run: cargo msrv verify --path mcumgr-toolkit --log-target=stdout --output-format=json

      - name: Check MSRV of mcumgrctl
        run: cargo msrv verify --path mcumgrctl --log-target=stdout --output-format=json

  semver:
    name: Semantic Versioning
    runs-on: ubuntu-latest
    needs: [lints, docs]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          manifest-path: mcumgr-toolkit/Cargo.toml

  # min-versions:
  #   name: Minimal Dependency Versions
  #   runs-on: ubuntu-latest
  #   needs: [lints, docs]
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v6

  #     - name: Install nightly toolchain
  #       uses: dtolnay/rust-toolchain@nightly

  #     - name: Install cargo-hack
  #       uses: taiki-e/install-action@cargo-hack
  #     - name: Install cargo-minimal-versions
  #       uses: taiki-e/install-action@cargo-minimal-versions

  #     - name: Check with minimal versions
  #       run: cargo minimal-versions check --workspace --ignore-private

  # min-versions-msrv:
  #   name: Minimal Dependency Versions (MSRV)
  #   runs-on: ubuntu-latest
  #   needs: [lints, docs]
  #   env:
  #     RUSTFLAGS: "-D warnings"
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v6

  #     - name: Install nightly toolchain
  #       uses: dtolnay/rust-toolchain@nightly

  #     - name: Install cargo-binstall
  #       uses: taiki-e/install-action@cargo-binstall
  #     - name: Install cargo-msrv
  #       run: cargo binstall --version 0.18.4 --no-confirm cargo-msrv
  #     - name: Install cargo-hack
  #       uses: taiki-e/install-action@cargo-hack
  #     - name: Install cargo-minimal-versions
  #       uses: taiki-e/install-action@cargo-minimal-versions

  #     - name: Determine MSRV
  #       run: echo "MSRV=$(cargo msrv --path mcumgr-toolkit show --output-format=minimal)" >> $GITHUB_ENV

  #     - name: Show MSRV
  #       run: echo "$MSRV"

  #     - name: Install MSRV Rust version
  #       run: rustup toolchain install "$MSRV"

  #     - name: Check with minimal versions
  #       run: cargo "+$MSRV" minimal-versions check --workspace --ignore-private

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo doc
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        run: cargo doc --no-deps

  leaks:
    name: Memory leaks
    runs-on: ubuntu-latest
    needs: [lints, docs]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install dependencies
        # llvm required to resolve symbols in sanitizer output
        run: sudo apt-get install -y llvm

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        env:
          RUSTFLAGS: "-Z sanitizer=address"
        run: cargo build --workspace --exclude mcumgr-toolkit-python --exclude mcumgr-toolkit-web --target x86_64-unknown-linux-gnu --tests

      - name: Run tests with leak sanitizer
        env:
          RUSTFLAGS: "-Z sanitizer=address"
        run: cargo test --workspace --exclude mcumgr-toolkit-python --exclude mcumgr-toolkit-web
          --target x86_64-unknown-linux-gnu --tests
          -- --test-threads 1

  release:
    name: Publish version
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'release'
    needs: [
        test,
        build-examples,
        build-cli,
        msrv,
        lints,
        docs,
        leaks,
        semver,
        # min-versions,
        # min-versions-msrv,
      ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Query crate version
        run: echo "lib_crate_version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: Query crate version
        run: echo "cli_crate_version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[1].version')" >> $GITHUB_ENV

      - name: Query release tag version
        run: echo "release_tag_version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Print versions
        run: echo "Lib Crate - ${{ env.lib_crate_version }}, CLI Crate - ${{ env.cli_crate_version }}, Release - ${{ env.release_tag_version }}"

      - name: Check lib version not empty
        run: test -n "${{ env.lib_crate_version }}"

      - name: Check cli version not empty
        run: test -n "${{ env.cli_crate_version }}"

      - name: Check matching version for lib
        run: test "${{ env.lib_crate_version }}" = "${{ env.release_tag_version }}"

      - name: Check matching version for cli
        run: test "${{ env.cli_crate_version }}" = "${{ env.release_tag_version }}"

      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Cargo publish
        run: cargo publish --workspace --exclude mcumgr-toolkit-python --exclude mcumgr-toolkit-web
